### ISSUE TITLE
How to run the server?

### ISSUE THREAD

**Issue by pengkunlunHIT** [yushulx/Android-IP-Camera#2]
I can run the client on my Android phone,but how to run the server on my computer?
When i import the whole Android-IP-Camera-Master project into Eclipse ADT,the new Android project only include the IPCamera file ,not including the Monitor file.
So i set up a new Java project and import the Monitor file.  

How to run the server on my computer?I really look forward to your wonderful help,thanks a lot!

**Comment by pengkunlunHIT** [comment]
I have successfully run the project.It do works great! Wonderful  job,it will be better if it could transfer sound.

**Comment by abdullah-19** [comment]
@pengkunlunHIT would you share how you build and ran this project ?
